import type { Metadata } from "next";
import { Plus_Jakarta_Sans, Roboto_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/layout/Footer";
import Navbar from "@/components/layout/Navbar";
import { ScreenSizeWrapper } from "@/components/layout/ScreenSizeWrapper";
import { Providers } from "./providers";
import "@rainbow-me/rainbowkit/styles.css";
import { ModalManager } from "@/components/modals/ModalManager";

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["500", "600", "700"],
});

const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Elipsys App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${plusJakartaSans.className} ${robotoMono.className} antialiased`}
      >
        <Providers>
          <ScreenSizeWrapper>
            <Navbar />
            <ModalManager />
            {children}
            <Footer />
          </ScreenSizeWrapper>
        </Providers>
      </body>
    </html>
  );
}
